#pragma config(Motor,  port2,           wheelMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           wheelMotor2,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           platform,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           tower,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           claw1,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           claw0,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           clawud0,       tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           clawud1,       tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//this is where variables are declared
int claw;
task main()
{
	claw=127;//this sets the initial position of the claw
	while(1) {
		motor(wheelMotor)=vexRT[Ch3];//this moves the wheel motors based on the joysticks position
		motor(wheelMotor2)=-vexRT[Ch3];//same as above
		motor(tower)=127*vexRT[Btn6U]-127*vexRT[Btn6D];// Same as below
		motor(platform)=127*vexRT[Btn5U]-127*vexRT[Btn5D];//the 127 is the speed of the motor and the btn is either 1 or 0
		motor(claw0)=claw;//Same as below
		motor(claw1)=-claw;//this opens or closes the claw based on the claw variable
		motor(clawud0)=vexRT[Ch2]*(110/120);
		motor(clawud1)=-vexRT[Ch2]*(110/120);//these affect the claws up and down motion
		if ((getTimer(timer1,seconds)>=.25) && vexRT[Btn8U]==1) {// this checks to make sure this hasnt happened and the right button is being pressed
			if(claw==127) {
				claw=57;//this determines what the claw variable should be
			}
			else{
				claw=127;
			}
			resetTimer(timer1);
		}
	}
}
